### ISSUE TITLE
Need to increase shm size when using PyTorch DataLoader

### ISSUE THREAD

**Issue by MRrollingJerry** [NVAITC/ai-lab#5]
**Describe the bug**
I was using google could platform. When using dataloader, multiprocessing=True, got thread is killed: bus error because docker limits resources.

**Solution**
When opening jupyter notebook in the shell, run 
sudo nvidia-docker run --shm-size=1g --rm -p 8888:8888 -v /home/$USER:/home/jovyan nvaitc/ai-lab
instead of 
sudo nvidia-docker run --rm -p 8888:8888 -v /home/$USER:/home/jovyan nvaitc/ai-lab

The new command assigns 1 GB to the container which allows multiprocessing

**Comment by tlkh** [comment]
To-do:

- [x] Update documentation
