### ISSUE TITLE
Add instructions for accessing notebook via other ports

### ISSUE THREAD

**Issue by MRrollingJerry** [NVAITC/ai-lab#6]
When you are using cloud, you probably will need to access jupyter notebook via ports other than 8888

By default, the command 
sudo nvidia-docker run --rm -p 8888:8888 -v /home/$USER:/home/jovyan nvaitc/ai-lab
allows you to access jupyter notebook through port 8888

If you wish accessing other ports, add the port you want to access to your firewall rule and then run
sudo nvidia-docker run --rm -p [new port]:8888 -v /home/$USER:/home/jovyan nvaitc/ai-lab

**Comment by tlkh** [comment]
To-do:

- [x] Update documentation
